#!/bin/bash
PP=`which python`

if [[ $PP == *"/home"* ]]; then
  echo "Don't use these scripts inside a virtualenv!"
  exit 1
fi

DEPS="-d python-virtualenv"
VERSION=`grep version setup.py | awk -F"'" '{print $2}'`

if [ ! -e /opt/ducted ];
then
    sudo virtualenv /opt/ducted
    sudo /opt/ducted/bin/pip install --upgrade pip
fi
sudo cp -a . /opt/ducted/duct
sudo rm -rf /opt/ducted/duct/ve
sudo rm -rf /opt/ducted/duct/.git
sudo rm -rf /opt/ducted/duct/.gitignore
sudo rm -rf /opt/ducted/duct/.travis.yml

sudo find /opt/ducted/duct -name "*.pyc" -delete
sudo find /opt/ducted/duct -name "*.pyc" -delete

sudo chown -R root.root /opt/ducted

cd /opt/ducted/duct
sudo /opt/ducted/bin/pip install -e .

cd -

sudo /usr/local/bin/fpm -s dir -t rpm -n duct --iteration el7 $DEPS -a x86_64 --after-install scripts/rhel/post-install.sh --rpm-init scripts/rhel/duct -v $VERSION /opt/ducted
