#!/bin/bash
PP=`which python`

if [[ $PP == *"/home"* ]]; then
  echo "Don't use these scripts inside a virtualenv!"
  exit 1
fi

DEPS="-d python-crypto -d python-twisted -d protobuf-python -d PyYAML -d pyOpenSSL"

fpm -s python -t rpm --no-python-dependencies --after-install scripts/rhel/post-install.sh --rpm-init scripts/rhel/duct $DEPS -a noarch --iteration el7 -n duct setup.py
